#### BOW,TFIDF,Machine Learning Algorithms

1. Preprocessing And Cleaning
2. Train Test Split
3. BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}
4. Trained Our Models


In [6]:
import os
print(os.getcwd())

c:\Users\Vethika\NlTP_Text_preprocessing


In [7]:
import pandas as pd
messages = pd.read_csv('../NlTP_Text_preprocessing\SMSSpamCollection (3).txt', 
                       sep='\t', 
                       names=["label", "message"])

In [8]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vethika\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [11]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [12]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [13]:
## Output Features
y=pd.get_dummies(messages['label'])

In [14]:
y=y.iloc[:,0].values

In [15]:
y

array([ True,  True, False, ...,  True,  True,  True])

## Create Bag Of Words

In [16]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [17]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [18]:
len(X_train),len(y_train)

(4457, 4457)

In [19]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [20]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [21]:
cv.vocabulary_

{'babe': 133,
 'talk': 2044,
 'think': 2101,
 'good': 816,
 'boy': 207,
 'miss': 1302,
 'love': 1201,
 'know': 1077,
 'need': 1394,
 'get': 760,
 'hotel': 963,
 'got': 831,
 'invit': 1020,
 'sweet': 2030,
 'come': 379,
 'english': 601,
 'bloke': 181,
 'need get': 1397,
 'co': 360,
 'want': 2325,
 'thing': 2100,
 'horribl': 959,
 'gal': 744,
 'knew': 1076,
 'dat': 482,
 'go': 793,
 'wif': 2391,
 'yest': 2485,
 'still': 1975,
 'ask': 101,
 'watch': 2344,
 'tv': 2198,
 'lor': 1189,
 'funni': 741,
 'wat': 2340,
 'izzit': 1033,
 'thk': 2107,
 'us': 2269,
 'watch tv': 2347,
 'week': 2363,
 'da': 472,
 'tri': 2177,
 'call': 239,
 'repli': 1714,
 'sm': 1899,
 'video': 2288,
 'mobil': 1316,
 'min': 1288,
 'unlimit': 2229,
 'text': 2077,
 'free': 712,
 'camcord': 275,
 'del': 506,
 'tri call': 2178,
 'call repli': 261,
 'min unlimit': 1294,
 'unlimit text': 2230,
 'text free': 2081,
 'free camcord': 715,
 'camcord repli': 276,
 'repli call': 1715,
 'cool': 423,
 'readi': 1678,
 'cool text': 424,

In [22]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [24]:
y_pred=spam_detect_model.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score,classification_report

In [26]:
accuracy_score(y_test,y_pred)

0.9838565022421525

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.95      0.93      0.94       151
        True       0.99      0.99      0.99       964

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



## Creating The TF-IDF Model

In [28]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [29]:
len(corpus)

5572

In [30]:
len(X_train),len(X_test)

(4457, 1115)

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [32]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.581, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.278, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0,

In [33]:
tv.vocabulary_

{'that': 2124,
 'cool': 430,
 'sometim': 1960,
 'slow': 1936,
 'gentl': 779,
 'hard': 907,
 'that cool': 2125,
 'wake': 2331,
 'sinc': 1920,
 'check': 324,
 'stuff': 2035,
 'saw': 1831,
 'true': 2204,
 'avail': 116,
 'space': 1979,
 'pl': 1609,
 'call': 235,
 'send': 1862,
 'mail': 1275,
 'pl call': 1610,
 'yesterday': 2488,
 'go': 804,
 'home': 961,
 'go home': 811,
 'di': 528,
 'yiju': 2490,
 'ju': 1081,
 'ur': 2258,
 'case': 295,
 'havent': 912,
 'sent': 1872,
 'num': 1488,
 'nd': 1434,
 'attempt': 108,
 'contract': 425,
 'week': 2373,
 'top': 2181,
 'prize': 1685,
 'either': 598,
 'cash': 296,
 'nd attempt': 1435,
 'cash prize': 301,
 'prize call': 1686,
 'ok': 1504,
 'way': 2359,
 'use': 2289,
 'stamp': 1998,
 'countri': 442,
 'good': 830,
 'lectur': 1164,
 'tell': 2094,
 'half': 893,
 'hr': 987,
 'come': 385,
 'need': 1438,
 'prepar': 1671,
 'hi': 934,
 'meet': 1317,
 'tmr': 2158,
 'dont': 556,
 'think': 2129,
 'card': 290,
 'uk': 2235,
 'travel': 2195,
 'ask': 98,
 'someon': 195

In [34]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [35]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score,classification_report
score=accuracy_score(y_test,y_pred)
print(score)

0.9775784753363229


In [37]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

       False       0.84      1.00      0.91       129
        True       1.00      0.97      0.99       986

    accuracy                           0.98      1115
   macro avg       0.92      0.99      0.95      1115
weighted avg       0.98      0.98      0.98      1115

